spring:
  application:
    name: order-service
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/order?useSSL=false
    username: admin
    password: admin
  account-datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/account?useSSL=false
    username: admin
    password: admin
  product-datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/product?useSSL=false
    username: admin
    password: admin

hibernate:
  hbm2ddl:
    auto: update
  dialect: org.hibernate.dialect.MySQL5Dialect

#management:
#  endpoints:
#   web:
#    exposure:
#     include: *
#  endpoint:
#   health:
#    show-details: always
#  health:
#   circuitbreakers:
#    enabled: true
#   ratelimiters:
#    enabled: true

#resilience4j.circuitbreaker:
#  instances:
#    pressureTest:
#      registerHealthIndicator: true
#      slowCallDurationThreshold: 1000
#      slowCallRateThreshold: 50
#      waitDurationInOpenState: 60s
#      maxWaitDurationInHalfOpenState: 10
#      ringBufferSizeInHalfOpenState: 200
#      slidingWindowSize: 100
